preferred_syntax = :sass
http_path = '/'
css_dir = 'css'
sass_dir = 'sass'
images_dir = 'img'
javascripts_dir = 'js'
relative_assets = true
line_comments = true
output_style = :compressed
# Sass::Script::Number.precision = 10